version: "3.8"

services:
  #https://opentelemetry.io/docs/net/getting-started/
  #https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/examples
  #https://www.jaegertracing.io/docs/1.22/getting-started/
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      #- 9411:9411

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
