version: "3.8"

services:
  #https://opentelemetry.io/docs/net/getting-started/
  #https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/examples
  #https://www.jaegertracing.io/docs/1.22/getting-started/
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    # volumes:
    # - ./.docker-compose/jaegertracing:/usr/share/jaegertracing/data
    # environment:
    # - xpack.monitoring.enabled=true
    # - xpack.watcher.enabled=false
    # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # - discovery.type=single-node
    # networks:
    # - elastic
