version: "3.8"

services:
  #https://opentelemetry.io/docs/net/getting-started/
  #https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/examples
  #https://www.jaegertracing.io/docs/1.22/getting-started/
  #https://rehansaeed.com/exporting-open-telemetry-data-to-jaeger/
  jaeger:
    #image: jaegertracing/all-in-one
    image: jaegertracing/opentelemetry-all-in-one
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686 #ui dashboard
      - 14268:14268
      - 14250:14250
      #- 9411:9411
      - 4317:55680 #4317 is the new port oltp port, old was 55680
      - 13133:13133 #health check

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
